package model;
// Generated 25/09/2018 14:00:12 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private Integer funcCod;
     private Departamento departamento;
     private String funcNome;
     private String funcSobrenome;
     private String funcCpf;
     private String funcPerfil;
     private Set users = new HashSet(0);

    public Funcionario() {
    }

	
    public Funcionario(Departamento departamento, String funcNome, String funcSobrenome) {
        this.departamento = departamento;
        this.funcNome = funcNome;
        this.funcSobrenome = funcSobrenome;
    }
    public Funcionario(Departamento departamento, String funcNome, String funcSobrenome, String funcCpf, String funcPerfil, Set users) {
       this.departamento = departamento;
       this.funcNome = funcNome;
       this.funcSobrenome = funcSobrenome;
       this.funcCpf = funcCpf;
       this.funcPerfil = funcPerfil;
       this.users = users;
    }
   
    public Integer getFuncCod() {
        return this.funcCod;
    }
    
    public void setFuncCod(Integer funcCod) {
        this.funcCod = funcCod;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getFuncNome() {
        return this.funcNome;
    }
    
    public void setFuncNome(String funcNome) {
        this.funcNome = funcNome;
    }
    public String getFuncSobrenome() {
        return this.funcSobrenome;
    }
    
    public void setFuncSobrenome(String funcSobrenome) {
        this.funcSobrenome = funcSobrenome;
    }
    public String getFuncCpf() {
        return this.funcCpf;
    }
    
    public void setFuncCpf(String funcCpf) {
        this.funcCpf = funcCpf;
    }
    public String getFuncPerfil() {
        return this.funcPerfil;
    }
    
    public void setFuncPerfil(String funcPerfil) {
        this.funcPerfil = funcPerfil;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


