package model;
// Generated 25/09/2018 14:00:12 by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer usCod;
     private Funcionario funcionario;
     private String usLogin;
     private String usPassword;

    public User() {
    }

	
    public User(Funcionario funcionario, String usPassword) {
        this.funcionario = funcionario;
        this.usPassword = usPassword;
    }
    public User(Funcionario funcionario, String usLogin, String usPassword) {
       this.funcionario = funcionario;
       this.usLogin = usLogin;
       this.usPassword = usPassword;
    }
   
    public Integer getUsCod() {
        return this.usCod;
    }
    
    public void setUsCod(Integer usCod) {
        this.usCod = usCod;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public String getUsLogin() {
        return this.usLogin;
    }
    
    public void setUsLogin(String usLogin) {
        this.usLogin = usLogin;
    }
    public String getUsPassword() {
        return this.usPassword;
    }
    
    public void setUsPassword(String usPassword) {
        this.usPassword = usPassword;
    }




}


