package view;

import controller.ControllerDep;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin
 */
public class CadastroDepartamento extends javax.swing.JFrame {

    private ControllerDep ctrDep;

    public CadastroDepartamento(ControllerDep pCtr) {
        initComponents();
        ctrDep = pCtr;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ButtonCadDep = new javax.swing.JButton();
        ButtonCancDep = new javax.swing.JButton();
        TextFieldNomeDep = new javax.swing.JTextField();
        TextFieldSiglaDep = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaDes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ButtonCadDep.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ButtonCadDep.setText("Cadastrar");
        ButtonCadDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCadDepActionPerformed(evt);
            }
        });

        ButtonCancDep.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ButtonCancDep.setText("Fechar");
        ButtonCancDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancDepActionPerformed(evt);
            }
        });

        TextFieldNomeDep.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        TextFieldSiglaDep.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome: ");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Descrição: ");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sigla: ");

        TextAreaDes.setColumns(20);
        TextAreaDes.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TextAreaDes.setRows(5);
        jScrollPane1.setViewportView(TextAreaDes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ButtonCadDep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonCancDep))
                    .addComponent(TextFieldNomeDep)
                    .addComponent(TextFieldSiglaDep)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextFieldNomeDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addComponent(TextFieldSiglaDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCadDep)
                    .addComponent(ButtonCancDep))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCancDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancDepActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonCancDepActionPerformed

    private void ButtonCadDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCadDepActionPerformed

        if (TextFieldNomeDep.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Campo de Nome Vazio, por favor preencha-o", "ERRO",
                    JOptionPane.ERROR_MESSAGE);

        } else if (TextFieldSiglaDep.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Campo de Sigla Vazio, por favor preencha-o", "ERRO",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            ctrDep.CadastraDepartamento(TextFieldNomeDep.getText(),
                    TextFieldSiglaDep.getText(),
                    TextAreaDes.getText());
            JOptionPane.showMessageDialog(this,
                    "Cadastro Realizado com Sucesso!", "Cadastro Realizado",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonCadDepActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCadDep;
    private javax.swing.JButton ButtonCancDep;
    private javax.swing.JTextArea TextAreaDes;
    private javax.swing.JTextField TextFieldNomeDep;
    private javax.swing.JTextField TextFieldSiglaDep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
