/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import model.Contato;

/**
 *
 * @author Rodrigo Maia
 */
public class CellDepart extends javax.swing.JPanel {

    private javax.swing.JPanel parent;
    private Controller ctrApp;
    private int codigoDep;
    private JScrollPane scrollCont;
    private JPanel panelCont;
    private ArrayList<CellContact> cellContacts;
    private boolean extendedCell;
    
    /**
     * Creates new form CellDepart
     */
    public CellDepart(Controller ctrApp,String nomeDep,
            String siglaDep, int codigoDep) {
        initComponents();
        
        this.ctrApp = ctrApp;
        this.parent = parent;
        this.codigoDep = codigoDep;
        labelNome.setText(nomeDep);
        labelSigla.setText(siglaDep);        
        this.setVisible(true);
        extendedCell = false;
                
        cellContacts = new ArrayList<CellContact> ();
    }

    //Metodo responsavel pela atualização da celula de funcionarios
    public void expContacts(ArrayList<Contato> listContacts){
        this.setMinimumSize(new Dimension(210,50));       //           
                
        panelCont = new JPanel();//Gerar painel de contatos
        panelCont.setLayout(new BoxLayout(panelCont, BoxLayout.Y_AXIS));        
        panelCont.setMaximumSize(new Dimension(210,250));
      
        //Carregar contatos na interface grafica        
        for(Contato c : listContacts){            
            CellContact cc = new CellContact(ctrApp,c.getNome(),
                    c.getSobrenome(),c.getPerfil(),c.getCodigo());
            cellContacts.add(cc);
            panelCont.add(cc);
        }      
        
        scrollCont = new JScrollPane(panelCont);        
       //Decidindo altura da celula conforme numero de contatos
        int height = 300;
        if(listContacts.size()<5){            
            height = (listContacts.size()*50);
        }
           
        //aplicando altura
        panelCont.setSize(210,height);            
        scrollCont.setSize(210,height);           
        this.setMaximumSize(new Dimension(210,50 + height));
        this.setSize(new Dimension(210, 50 + height));        
 
        this.add(scrollCont);
        extendedCell = true;
        this.updateUI();
    }

    void minContacts() {
        
        if(panelCont != null){
            panelCont.removeAll();
            panelCont = null;
        }
        
        if(scrollCont != null){
            this.remove(scrollCont);
            scrollCont.removeAll();
            scrollCont = null;
        }
        
        cellContacts.clear(); 
        this.setMaximumSize(new Dimension(210,50));
        this.setSize(210,50);
        extendedCell = false;
    }
    
    
    public int getCodigoDep() {
        return codigoDep;    
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelNome = new javax.swing.JLabel();
        labelSigla = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(210, 50));
        setMinimumSize(new java.awt.Dimension(210, 50));
        setPreferredSize(new java.awt.Dimension(210, 50));
        setRequestFocusEnabled(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(208, 50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNome.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        labelNome.setText("Nome Departamento");
        jPanel1.add(labelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 17));

        labelSigla.setText("sigla");
        jPanel1.add(labelSigla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 137, -1));

        add(jPanel1);

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
        this.setBackground(new Color(0,51,255));
        labelNome.setForeground(new Color(255,255,255));
        labelSigla.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
        this.setBackground(new Color(153,204,255));
        labelNome.setForeground(new Color(0,0,0));
        labelSigla.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_formMouseExited

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if(!extendedCell){
           ctrApp.expToContacts("" + codigoDep);
        }
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelSigla;
    // End of variables declaration//GEN-END:variables

   
}
