/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import java.awt.Dimension;

/**
 *
 * @author Rodrigo Maia
 */
public class CellDepart extends javax.swing.JPanel {

    private javax.swing.JPanel parent;
    private Controller ctrApp;
    private int codigoDep;
    
    /**
     * Creates new form CellDepart
     */
    public CellDepart(Controller ctrApp,String nomeDep,String siglaDep, int codigoDep) {
        initComponents();
        
        this.parent = parent;
        labelNome.setText(nomeDep);
        labelSigla.setText(siglaDep);        
        this.setVisible(true);
    }

    //Metodo responsavel pela atualização da celula de funcionarios
    public void expContacts(){
        this.setPreferredSize(new Dimension(210,300));
        this.setMaximumSize(new Dimension(210,300));
        this.setMinimumSize(new Dimension(210,300));
        this.setSize(new Dimension(210, 300));        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNome = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        labelSigla = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(210, 50));
        setMinimumSize(new java.awt.Dimension(210, 50));
        setPreferredSize(new java.awt.Dimension(210, 50));
        setRequestFocusEnabled(false);

        labelNome.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        labelNome.setText("Nome Departamento");

        jButton1.setText("^");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        labelSigla.setText("sigla");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNome, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(labelSigla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelSigla)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    //Botão para fazer a requisição dos dados
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       ctrApp.expToContacts(""+codigoDep);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelSigla;
    // End of variables declaration//GEN-END:variables
}
