/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionAdapter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Departamento;
import model.Funcionario;

/**
 *
 * @author Rodrigo Maia
 */
public class MainWindow extends javax.swing.JFrame {

    private static Point point = new Point();
    private JFrame t = this;
    private Controller ctrApp;

    /**
     * Creates new form MainWindow
     */
    public MainWindow(Controller actrApp) {
        initComponents();
        initComponentsExtra();

        this.ctrApp = actrApp;
    }

    public void initComponentsExtra() {

        this.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                point.x = e.getX();
                point.y = e.getY();
            }
        });

        this.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent e) {
                Point p = t.getLocation();
                t.setLocation(p.x + e.getX() - point.x, p.y + e.getY() - point.y);
            }
        });

        this.mainBar.setVisible(false);
    }

    public void loginOk() {
        this.censoredFrame.setVisible(false);
        this.mainBar.setVisible(true);
    }

    public void callMessage(String msg, String title, int typeMsg) {
        JOptionPane.showMessageDialog(this, msg, title, typeMsg);
    }

    public void addDeps() {
        ArrayList<Departamento> listaDeps = ctrApp.getCtrDep().getListaDeps();
        int x = 0;
        for (Departamento dp : listaDeps) {
            JComboBox combo = new JComboBox(new String[]{dp.getSigla() + "-" + dp.getNome()});
            combo.setBounds(0, x, 200, 35);
            combo.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {
                }

                @Override
                public void mousePressed(MouseEvent e) {
                    //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                    //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    if (combo.getItemCount() == 1) {
                        ctrApp.expToContacts("" + dp.getCodigo());
                        System.out.println(dp.getCodigo());
                        ArrayList<Funcionario> funcs = ctrApp.getCtrFunc().getListFuncs();
                        for (Funcionario f : funcs) {
                            combo.addItem(f.getNome() + " " + f.getSobrenome());

                        }
                    }
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }
            });
            tabCont.add(combo);
            x += 36;
        }
        tabCont.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        censoredFrame = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        cxTxtLogin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        cxPassword = new javax.swing.JPasswordField();
        superBody = new javax.swing.JPanel();
        painelChats = new javax.swing.JPanel();
        managerTab = new javax.swing.JTabbedPane();
        tabCont = new javax.swing.JPanel();
        tabRec = new javax.swing.JPanel();
        titleChat = new javax.swing.JPanel();
        bodyChat = new javax.swing.JPanel();
        cxTextMsg = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        ButtonEnviar = new javax.swing.JButton();
        mainBar = new javax.swing.JMenuBar();
        menuNovo = new javax.swing.JMenu();
        cadFunc = new javax.swing.JMenuItem();
        cadDep = new javax.swing.JMenuItem();
        menuCons = new javax.swing.JMenu();
        colFunc = new javax.swing.JMenuItem();
        colDep = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Comucop 1.0");
        setBackground(new java.awt.Color(0, 0, 102));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        censoredFrame.setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        jPanel1.setForeground(new java.awt.Color(204, 204, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 260));

        cxTxtLogin.setBackground(new java.awt.Color(153, 153, 153));
        cxTxtLogin.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password:");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Login:");

        jButton2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 102, 102));
        jButton2.setText("Sign in");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cxPassword.setBackground(new java.awt.Color(153, 153, 153));
        cxPassword.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cxTxtLogin)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cxPassword))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cxTxtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cxPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(40, 40, 40))
        );

        censoredFrame.add(jPanel1);

        getContentPane().add(censoredFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 420));

        superBody.setBackground(new java.awt.Color(255, 255, 255));
        superBody.setForeground(new java.awt.Color(255, 255, 255));
        superBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelChats.setBackground(new java.awt.Color(0, 0, 153));

        managerTab.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        managerTab.setToolTipText("");

        tabCont.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout tabContLayout = new javax.swing.GroupLayout(tabCont);
        tabCont.setLayout(tabContLayout);
        tabContLayout.setHorizontalGroup(
            tabContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );
        tabContLayout.setVerticalGroup(
            tabContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );

        managerTab.addTab("Contantos", tabCont);

        tabRec.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout tabRecLayout = new javax.swing.GroupLayout(tabRec);
        tabRec.setLayout(tabRecLayout);
        tabRecLayout.setHorizontalGroup(
            tabRecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );
        tabRecLayout.setVerticalGroup(
            tabRecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );

        managerTab.addTab("Recentes", tabRec);

        javax.swing.GroupLayout painelChatsLayout = new javax.swing.GroupLayout(painelChats);
        painelChats.setLayout(painelChatsLayout);
        painelChatsLayout.setHorizontalGroup(
            painelChatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(managerTab)
        );
        painelChatsLayout.setVerticalGroup(
            painelChatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelChatsLayout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(managerTab, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        superBody.add(painelChats, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 420));

        titleChat.setBackground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout titleChatLayout = new javax.swing.GroupLayout(titleChat);
        titleChat.setLayout(titleChatLayout);
        titleChatLayout.setHorizontalGroup(
            titleChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        titleChatLayout.setVerticalGroup(
            titleChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        superBody.add(titleChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 590, 40));

        bodyChat.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout bodyChatLayout = new javax.swing.GroupLayout(bodyChat);
        bodyChat.setLayout(bodyChatLayout);
        bodyChatLayout.setHorizontalGroup(
            bodyChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        bodyChatLayout.setVerticalGroup(
            bodyChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        superBody.add(bodyChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 590, 310));

        jTextPane1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cxTextMsg.setViewportView(jTextPane1);

        superBody.add(cxTextMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 510, 70));

        ButtonEnviar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ButtonEnviar.setText("Enviar");
        ButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEnviarActionPerformed(evt);
            }
        });
        superBody.add(ButtonEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 350, -1, -1));

        getContentPane().add(superBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 420));

        mainBar.setBackground(new java.awt.Color(0, 0, 102));
        mainBar.setBorder(null);
        mainBar.setAlignmentX(0.0F);

        menuNovo.setBackground(new java.awt.Color(0, 0, 102));
        menuNovo.setForeground(new java.awt.Color(255, 255, 255));
        menuNovo.setText("Novo");

        cadFunc.setText("Funcionário");
        cadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadFuncActionPerformed(evt);
            }
        });
        menuNovo.add(cadFunc);

        cadDep.setText("Departamento");
        cadDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadDepActionPerformed(evt);
            }
        });
        menuNovo.add(cadDep);

        mainBar.add(menuNovo);

        menuCons.setBackground(new java.awt.Color(0, 0, 102));
        menuCons.setForeground(new java.awt.Color(255, 255, 255));
        menuCons.setText("Consultar");

        colFunc.setText("Funcionário");
        colFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colFuncActionPerformed(evt);
            }
        });
        menuCons.add(colFunc);

        colDep.setText("Departamento");
        colDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colDepActionPerformed(evt);
            }
        });
        menuCons.add(colDep);

        mainBar.add(menuCons);

        setJMenuBar(mainBar);
        mainBar.getAccessibleContext().setAccessibleName("");
        mainBar.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            ctrApp.tryEstablishCon(cxTxtLogin.getText(), cxPassword.getText());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void cadDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadDepActionPerformed
        // TODO add your handling code here:
        ctrApp.getCtrDep().AbreJanela(1);
    }//GEN-LAST:event_cadDepActionPerformed

    private void colDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colDepActionPerformed

        ctrApp.getCtrDep().AbreJanela(3);
        // TODO add your handling code here:
    }//GEN-LAST:event_colDepActionPerformed

    private void cadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadFuncActionPerformed
        // TODO add your handling code here:
        ctrApp.getCtrFunc().AbreJanela(1);
    }//GEN-LAST:event_cadFuncActionPerformed

    private void colFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colFuncActionPerformed
        // TODO add your handling code here:
        ctrApp.getCtrFunc().AbreJanela(3);
    }//GEN-LAST:event_colFuncActionPerformed

    private void ButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonEnviarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEnviar;
    private javax.swing.JPanel bodyChat;
    private javax.swing.JMenuItem cadDep;
    private javax.swing.JMenuItem cadFunc;
    private javax.swing.JPanel censoredFrame;
    private javax.swing.JMenuItem colDep;
    private javax.swing.JMenuItem colFunc;
    private javax.swing.JPasswordField cxPassword;
    private javax.swing.JScrollPane cxTextMsg;
    private javax.swing.JTextField cxTxtLogin;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JMenuBar mainBar;
    private javax.swing.JTabbedPane managerTab;
    private javax.swing.JMenu menuCons;
    private javax.swing.JMenu menuNovo;
    private javax.swing.JPanel painelChats;
    private javax.swing.JPanel superBody;
    private javax.swing.JPanel tabCont;
    private javax.swing.JPanel tabRec;
    private javax.swing.JPanel titleChat;
    // End of variables declaration//GEN-END:variables
}
