
package view;

import controller.Controller;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.io.IOException;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import model.Chat;
import model.Contato;
import model.Departamento;


public class MainWindow extends javax.swing.JFrame {

    private static Point point = new Point();
    private JFrame t = this;
    private Controller ctrApp;
    private ArrayList<CellDepart> listDeparts;
    private ArrayList<CellChat> listChats;
    

    //Metodo construtor
    public MainWindow(Controller actrApp) {
        //Inicializa os componentes da main window
        initComponents();
        initComponentsExtra();
        //Atribui o controle principal a ctrApp
        this.ctrApp = actrApp;
        listChats = new ArrayList<CellChat>();
    }
    
    //Componentes extras são listeners do mouse, e deixar certos campos não visiveis
    public void initComponentsExtra() {

        this.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                point.x = e.getX();
                point.y = e.getY();
            }
        });

        this.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent e) {
                Point p = t.getLocation();
                t.setLocation(p.x + e.getX() - point.x, p.y + e.getY() - point.y);
            }
        });
        //Deixa invisivel componentes relativos ao chat
        this.mainBar.setVisible(false);
        superBody.setVisible(false);
        bodyChat.setVisible(false);
        ButtonEnviar.setVisible(false);
        cxTextMsg.setVisible(false);
        chatHead.setVisible(false);
    }
    
    //Caso o login esteja ok, deixará visivel o chat em si
    public void loginOk() {
        this.censoredFrame.setVisible(false);
        this.mainBar.setVisible(true);
        superBody.setVisible(true);
    }
    
    public void callMessage(String msg, String title, int typeMsg) {
        JOptionPane.showMessageDialog(this, msg, title, typeMsg);
    }

    //Metodo responsável por adicionar departamentos na view
    public void addDeps() {
        //Recebe a lista de departamentos
        ArrayList<Departamento> listaDeps = ctrApp.getCtrDep().getListaDeps();
       
        //Ira passar por todos os departamentos adicionando os na listDeparts
        listDeparts = new ArrayList<CellDepart>();
        for (Departamento dp : listaDeps) {
            //Aloca um departamento no formato de celulas separadas
            CellDepart cellDep = new CellDepart(ctrApp,dp.getNome(),dp.getSigla(),dp.getCodigo());
            //Adiciona essa celula na lista de departamentos e no painel que mostra os dps
            listDeparts.add(cellDep);
            panelCont.add(cellDep);
        }
        tabCont.updateUI();
    }
    
    //Metodo responsável por adicionar os chats na view
    public void addChats(){
        int i = 0;
        //Recebe os chats
        ArrayList<Chat> chats = ctrApp.getListChats();
        //Para cada chat criará uma celula para colocar os dados do chat
        for (Chat c : chats) {
            Contato cont = c.getDestinatario();
            CellChat cellChat = new CellChat(ctrApp,(cont.getNome() + cont.getSobrenome()),
                    cont.getPerfil(),c.getLastMsg(),c.countUnreadMsg(),i);
            //Adiciona a celula de chat tanto na listChats quanto no panel de conversas
            listChats.add(cellChat);
            panelRec.add(cellChat);
            i++;
        }
        tabRec.updateUI();        
    }
    
    //Metodo responsavel por atualizar os chats
    public void updateChat(){
        panelRec.removeAll();
        listChats.clear();
        addChats();
    }
    
    //Metodo responsavel por realizar o preenchimento dos contatos para um determinado dp
    public void expCellDeparts(int depart,ArrayList<Contato> listCont) {
        //Percorrerá todos os departamentos, caso seja o departamento clicado preencherá,
        //se não for irá minimizar os contatos de outros departamentos
        for(CellDepart cd : listDeparts){
            if(cd.getCodigoDep()==depart){
                cd.expContacts(listCont);               
            }else {
                cd.minContacts();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        censoredFrame = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        cxTxtLogin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        cxPassword = new javax.swing.JPasswordField();
        btn_conf = new javax.swing.JButton();
        superBody = new javax.swing.JPanel();
        painelChats = new javax.swing.JPanel();
        managerTab = new javax.swing.JTabbedPane();
        tabCont = new javax.swing.JPanel();
        scrolPaneCont = new javax.swing.JScrollPane();
        panelCont = new javax.swing.JPanel();
        tabRec = new javax.swing.JPanel();
        scrollPaneRec = new javax.swing.JScrollPane();
        panelRec = new javax.swing.JPanel();
        titleChat = new javax.swing.JPanel();
        chatHead = new javax.swing.JPanel();
        panelLetra = new javax.swing.JPanel();
        primLetra = new javax.swing.JLabel();
        nomeContato = new javax.swing.JLabel();
        perfilContato = new javax.swing.JLabel();
        bodyChat = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        scrollTextMsg = new javax.swing.JScrollPane();
        cxTextMsg = new javax.swing.JTextPane();
        ButtonEnviar = new javax.swing.JButton();
        mainBar = new javax.swing.JMenuBar();
        menuNovo = new javax.swing.JMenu();
        cadFunc = new javax.swing.JMenuItem();
        cadDep = new javax.swing.JMenuItem();
        menuCons = new javax.swing.JMenu();
        colFunc = new javax.swing.JMenuItem();
        colDep = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Comucop 1.0");
        setBackground(new java.awt.Color(0, 0, 102));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        censoredFrame.setBackground(new java.awt.Color(51, 51, 51));
        censoredFrame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        jPanel1.setForeground(new java.awt.Color(204, 204, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 260));

        cxTxtLogin.setBackground(new java.awt.Color(153, 153, 153));
        cxTxtLogin.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password:");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Login:");

        jButton2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 102, 102));
        jButton2.setText("Sign in");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cxPassword.setBackground(new java.awt.Color(153, 153, 153));
        cxPassword.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cxTxtLogin)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 353, Short.MAX_VALUE))
                    .addComponent(cxPassword)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cxTxtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cxPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(37, 37, 37))
        );

        censoredFrame.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        btn_conf.setText("jButton1");
        btn_conf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confActionPerformed(evt);
            }
        });
        censoredFrame.add(btn_conf, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 30, -1));

        getContentPane().add(censoredFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 420));

        superBody.setBackground(new java.awt.Color(255, 255, 255));
        superBody.setForeground(new java.awt.Color(255, 255, 255));
        superBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelChats.setBackground(new java.awt.Color(0, 0, 153));

        managerTab.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        managerTab.setToolTipText("");

        tabCont.setBackground(new java.awt.Color(204, 204, 204));
        tabCont.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        scrolPaneCont.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrolPaneCont.setToolTipText("");
        scrolPaneCont.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrolPaneCont.setMaximumSize(new java.awt.Dimension(225, 372));
        scrolPaneCont.setMinimumSize(new java.awt.Dimension(225, 372));

        panelCont.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelCont.setLayout(new javax.swing.BoxLayout(panelCont, javax.swing.BoxLayout.Y_AXIS));
        scrolPaneCont.setViewportView(panelCont);

        javax.swing.GroupLayout tabContLayout = new javax.swing.GroupLayout(tabCont);
        tabCont.setLayout(tabContLayout);
        tabContLayout.setHorizontalGroup(
            tabContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrolPaneCont, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
        );
        tabContLayout.setVerticalGroup(
            tabContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrolPaneCont, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
        );

        managerTab.addTab("Contatos", tabCont);

        tabRec.setBackground(new java.awt.Color(204, 204, 204));

        scrollPaneRec.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPaneRec.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        panelRec.setLayout(new javax.swing.BoxLayout(panelRec, javax.swing.BoxLayout.Y_AXIS));
        scrollPaneRec.setViewportView(panelRec);

        javax.swing.GroupLayout tabRecLayout = new javax.swing.GroupLayout(tabRec);
        tabRec.setLayout(tabRecLayout);
        tabRecLayout.setHorizontalGroup(
            tabRecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPaneRec, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
        );
        tabRecLayout.setVerticalGroup(
            tabRecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPaneRec, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
        );

        managerTab.addTab("Conversas", tabRec);

        javax.swing.GroupLayout painelChatsLayout = new javax.swing.GroupLayout(painelChats);
        painelChats.setLayout(painelChatsLayout);
        painelChatsLayout.setHorizontalGroup(
            painelChatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(managerTab)
        );
        painelChatsLayout.setVerticalGroup(
            painelChatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelChatsLayout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(managerTab, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        superBody.add(painelChats, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 420));

        titleChat.setBackground(new java.awt.Color(0, 0, 153));
        titleChat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chatHead.setBackground(new java.awt.Color(0, 0, 153));
        chatHead.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLetra.setBackground(new java.awt.Color(255, 255, 255));

        primLetra.setBackground(new java.awt.Color(0, 0, 255));
        primLetra.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        primLetra.setForeground(new java.awt.Color(0, 0, 153));
        primLetra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        primLetra.setText("N");

        javax.swing.GroupLayout panelLetraLayout = new javax.swing.GroupLayout(panelLetra);
        panelLetra.setLayout(panelLetraLayout);
        panelLetraLayout.setHorizontalGroup(
            panelLetraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLetraLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(primLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelLetraLayout.setVerticalGroup(
            panelLetraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(primLetra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        chatHead.add(panelLetra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 32, 30));

        nomeContato.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        nomeContato.setForeground(new java.awt.Color(255, 255, 255));
        nomeContato.setText("Nome do contato");
        chatHead.add(nomeContato, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 0, 426, -1));

        perfilContato.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        perfilContato.setForeground(new java.awt.Color(255, 255, 255));
        perfilContato.setText("perfil");
        chatHead.add(perfilContato, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 19, 353, -1));

        titleChat.add(chatHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 40));

        superBody.add(titleChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 590, 40));

        bodyChat.setBackground(new java.awt.Color(204, 204, 204));

        TextArea.setColumns(20);
        TextArea.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TextArea.setRows(5);
        jScrollPane1.setViewportView(TextArea);

        javax.swing.GroupLayout bodyChatLayout = new javax.swing.GroupLayout(bodyChat);
        bodyChat.setLayout(bodyChatLayout);
        bodyChatLayout.setHorizontalGroup(
            bodyChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );
        bodyChatLayout.setVerticalGroup(
            bodyChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        superBody.add(bodyChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 590, 310));

        cxTextMsg.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        scrollTextMsg.setViewportView(cxTextMsg);

        superBody.add(scrollTextMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 510, 70));

        ButtonEnviar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ButtonEnviar.setText("Enviar");
        ButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEnviarActionPerformed(evt);
            }
        });
        superBody.add(ButtonEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 350, 80, 70));

        getContentPane().add(superBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 420));

        mainBar.setBackground(new java.awt.Color(0, 0, 102));
        mainBar.setBorder(null);
        mainBar.setAlignmentX(0.0F);

        menuNovo.setBackground(new java.awt.Color(0, 0, 102));
        menuNovo.setForeground(new java.awt.Color(255, 255, 255));
        menuNovo.setText("Novo");

        cadFunc.setText("Funcionário");
        cadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadFuncActionPerformed(evt);
            }
        });
        menuNovo.add(cadFunc);

        cadDep.setText("Departamento");
        cadDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadDepActionPerformed(evt);
            }
        });
        menuNovo.add(cadDep);

        mainBar.add(menuNovo);

        menuCons.setBackground(new java.awt.Color(0, 0, 102));
        menuCons.setForeground(new java.awt.Color(255, 255, 255));
        menuCons.setText("Consultar");

        colFunc.setText("Funcionário");
        colFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colFuncActionPerformed(evt);
            }
        });
        menuCons.add(colFunc);

        colDep.setText("Departamento");
        colDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colDepActionPerformed(evt);
            }
        });
        menuCons.add(colDep);

        mainBar.add(menuCons);

        setJMenuBar(mainBar);
        mainBar.getAccessibleContext().setAccessibleName("");
        mainBar.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Listener do botao responsalve pelo login
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            ctrApp.tryEstablishCon(cxTxtLogin.getText(), cxPassword.getText());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton2ActionPerformed
    
    //Metodo utilizado para deixar visivel o chat de uma conversa
    public void openTextUI(String nome, String perfil) {        
        nomeContato.setText(nome);
        perfilContato.setText(perfil);
        primLetra.setText(nome.substring(0,1));
        
        bodyChat.setVisible(true);
        cxTextMsg.setVisible(true);
        TextArea.setText("");
        ButtonEnviar.setVisible(true);
        chatHead.setVisible(true);
    }
    
    //Metodo utilizado para mostrar as msg da conversa
    public void preencheChat(String msgs){        
        TextArea.setText(msgs);
    }
    
     //Caso exista o chat entre os contatos, pode-se preencher com as msg e dados
    public void preencheChat(String msgs,String nome, String perfil){
        openTextUI(nome,perfil);         
        TextArea.setText(msgs);
    }
    
    //Caso o login de certo mostrará o chat em si
    public void backLoginWin() {
        this.mainBar.setVisible(false);
        superBody.setVisible(false);
        censoredFrame.setVisible(true);
    }
    
    private void cadDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadDepActionPerformed
       
        ctrApp.getCtrDep().AbreJanela(1);
    }//GEN-LAST:event_cadDepActionPerformed

    private void colDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colDepActionPerformed

        ctrApp.getCtrDep().AbreJanela(3);
       
    }//GEN-LAST:event_colDepActionPerformed

    private void cadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadFuncActionPerformed
        
        ctrApp.getCtrFunc().AbreJanela(1);
    }//GEN-LAST:event_cadFuncActionPerformed

    private void colFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colFuncActionPerformed
        
        ctrApp.getCtrFunc().AbreJanela(3);
    }//GEN-LAST:event_colFuncActionPerformed

    //Listener do botão utilizado para enviar msgs
    private void ButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEnviarActionPerformed
        // Se a msg não estiver vazia chamará os metodos para envio
        if(!cxTextMsg.getText().isEmpty()){
            ctrApp.sendMsg(cxTextMsg.getText());
            cxTextMsg.setText("");
        }
    }//GEN-LAST:event_ButtonEnviarActionPerformed
   
    //Listener utilizado para quando se deseja fechar a janela, assim irá comunicar o servidor que se está saindo
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
       // ctrApp.finishCon();
    }//GEN-LAST:event_formWindowClosed
    
    //Listener utilizado para quando se deseja fechar a janela, assim irá comunicar o servidor que se está saindo
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
       // ctrApp.finishCon();
    }//GEN-LAST:event_formWindowClosing

    //Botão para cnfiguração de IP
    private void btn_confActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confActionPerformed
        String ret = JOptionPane.showInputDialog(this,"Digite o ip do servidor:",
                ctrApp.getIPServer());
        if(ret.matches("([\\d ]{0,3}\\.){3}[\\d ]{0,3}")){//Validando IP
            try {            
                ctrApp.setIPServer(ret);//Aplicando configuração
            } catch (UnknownHostException ex) {//Mensagens de erro
                JOptionPane.showMessageDialog(this,ex.getMessage(),
                        "Erro ao aplicar configurações!!",JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this,"Valor de IP inválido!",
                    "Valor inválido para IP",JOptionPane.WARNING_MESSAGE);
        }                
    }//GEN-LAST:event_btn_confActionPerformed

    //Alguns metodos get e set
    public void changeTabRec() {
        managerTab.setSelectedIndex(1);
    }   
    
    public JTextArea getTextArea() {
        return TextArea;
    }

    public void setTextArea(JTextArea TextArea) {
        this.TextArea = TextArea;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEnviar;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JPanel bodyChat;
    private javax.swing.JButton btn_conf;
    private javax.swing.JMenuItem cadDep;
    private javax.swing.JMenuItem cadFunc;
    private javax.swing.JPanel censoredFrame;
    private javax.swing.JPanel chatHead;
    private javax.swing.JMenuItem colDep;
    private javax.swing.JMenuItem colFunc;
    private javax.swing.JPasswordField cxPassword;
    private javax.swing.JTextPane cxTextMsg;
    private javax.swing.JTextField cxTxtLogin;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar mainBar;
    private javax.swing.JTabbedPane managerTab;
    private javax.swing.JMenu menuCons;
    private javax.swing.JMenu menuNovo;
    private javax.swing.JLabel nomeContato;
    private javax.swing.JPanel painelChats;
    private javax.swing.JPanel panelCont;
    private javax.swing.JPanel panelLetra;
    private javax.swing.JPanel panelRec;
    private javax.swing.JLabel perfilContato;
    private javax.swing.JLabel primLetra;
    private javax.swing.JScrollPane scrolPaneCont;
    private javax.swing.JScrollPane scrollPaneRec;
    private javax.swing.JScrollPane scrollTextMsg;
    private javax.swing.JPanel superBody;
    private javax.swing.JPanel tabCont;
    private javax.swing.JPanel tabRec;
    private javax.swing.JPanel titleChat;
    // End of variables declaration//GEN-END:variables


   



}
