/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.JFrame;

/**
 *
 * @author Rodrigo Maia
 */
public class MainWindow extends javax.swing.JFrame {

     private static Point point = new Point(); 
     private JFrame t = this;
     private Controller ctrApp;
    /**
     * Creates new form MainWindow
     */
    public MainWindow(Controller actrApp) {
        initComponents();
        initComponentsExtra();
        
        this.ctrApp = actrApp;
    }
    
    public void initComponentsExtra(){
        
        this.addMouseListener(new MouseAdapter() {         
            @Override
            public void mousePressed(MouseEvent e) {
              point.x = e.getX();
              point.y = e.getY();
            }
        });
        
        this.addMouseMotionListener(new MouseMotionAdapter() {
          @Override
          public void mouseDragged(MouseEvent e) {
            Point p = t.getLocation();
            t.setLocation(p.x + e.getX() - point.x, p.y + e.getY() - point.y);
          }
        });
        
        this.mainBar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        censoredFrame = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        superBody = new javax.swing.JPanel();
        painelChats = new javax.swing.JPanel();
        managerTab = new javax.swing.JTabbedPane();
        tabRec = new javax.swing.JPanel();
        tabCont = new javax.swing.JPanel();
        mainBar = new javax.swing.JMenuBar();
        menuNovo = new javax.swing.JMenu();
        cadFunc = new javax.swing.JMenuItem();
        cadDep = new javax.swing.JMenuItem();
        menuCons = new javax.swing.JMenu();
        colFunc = new javax.swing.JMenuItem();
        colDep = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        censoredFrame.setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        jPanel1.setForeground(new java.awt.Color(204, 204, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 260));

        jTextField2.setBackground(new java.awt.Color(153, 153, 153));
        jTextField2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password:");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Login:");

        jButton2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 102, 102));
        jButton2.setText("Sign in");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPasswordField1.setBackground(new java.awt.Color(153, 153, 153));
        jPasswordField1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPasswordField1))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(40, 40, 40))
        );

        censoredFrame.add(jPanel1);

        getContentPane().add(censoredFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 420));

        superBody.setBackground(new java.awt.Color(255, 255, 255));
        superBody.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        superBody.setForeground(new java.awt.Color(255, 255, 255));
        superBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelChats.setBackground(new java.awt.Color(0, 0, 153));

        managerTab.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        managerTab.setToolTipText("");

        javax.swing.GroupLayout tabRecLayout = new javax.swing.GroupLayout(tabRec);
        tabRec.setLayout(tabRecLayout);
        tabRecLayout.setHorizontalGroup(
            tabRecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );
        tabRecLayout.setVerticalGroup(
            tabRecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        managerTab.addTab("Recentes", tabRec);

        javax.swing.GroupLayout tabContLayout = new javax.swing.GroupLayout(tabCont);
        tabCont.setLayout(tabContLayout);
        tabContLayout.setHorizontalGroup(
            tabContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );
        tabContLayout.setVerticalGroup(
            tabContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        managerTab.addTab("Contantos", tabCont);

        javax.swing.GroupLayout painelChatsLayout = new javax.swing.GroupLayout(painelChats);
        painelChats.setLayout(painelChatsLayout);
        painelChatsLayout.setHorizontalGroup(
            painelChatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(managerTab)
        );
        painelChatsLayout.setVerticalGroup(
            painelChatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(managerTab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );

        superBody.add(painelChats, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 420));

        getContentPane().add(superBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 420));

        mainBar.setBackground(new java.awt.Color(0, 0, 102));

        menuNovo.setBackground(new java.awt.Color(0, 0, 102));
        menuNovo.setForeground(new java.awt.Color(255, 255, 255));
        menuNovo.setText("Novo");

        cadFunc.setText("Funcionário");
        menuNovo.add(cadFunc);

        cadDep.setText("Departamento");
        cadDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadDepActionPerformed(evt);
            }
        });
        menuNovo.add(cadDep);

        mainBar.add(menuNovo);

        menuCons.setBackground(new java.awt.Color(0, 0, 102));
        menuCons.setForeground(new java.awt.Color(255, 255, 255));
        menuCons.setText("Consultar");

        colFunc.setText("Funcionário");
        menuCons.add(colFunc);

        colDep.setText("Departamento");
        menuCons.add(colDep);

        mainBar.add(menuCons);

        setJMenuBar(mainBar);
        mainBar.getAccessibleContext().setAccessibleName("");
        mainBar.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.censoredFrame.setVisible(false);
        this.mainBar.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cadDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadDepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadDepActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadDep;
    private javax.swing.JMenuItem cadFunc;
    private javax.swing.JPanel censoredFrame;
    private javax.swing.JMenuItem colDep;
    private javax.swing.JMenuItem colFunc;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JMenuBar mainBar;
    private javax.swing.JTabbedPane managerTab;
    private javax.swing.JMenu menuCons;
    private javax.swing.JMenu menuNovo;
    private javax.swing.JPanel painelChats;
    private javax.swing.JPanel superBody;
    private javax.swing.JPanel tabCont;
    private javax.swing.JPanel tabRec;
    // End of variables declaration//GEN-END:variables
}
